### ISSUE TITLE
Module not found: Can't resolve '@components/Layout'

### ISSUE THREAD

**Issue by henryejemuta** [goriyavipul/taskdemo#1]
![image](https://github.com/goriyavipul/taskdemo/assets/13375596/3fbf39c5-eb42-46af-9c1e-ea6c4cc3bbbf)

**Comment by goriyavipul** [comment]
Hi @henryejemuta 

I have added tsconfig file to access src folders using @. Look's like typescript is not install properly, It's working properly from my side. 

If you are still facing the issue let me know.

![image](https://github.com/goriyavipul/taskdemo/assets/82497125/ead98ff8-4e25-4337-a5c1-3796246956a7)

**Comment by henryejemuta** [comment]
@goriyavipul issue isn't fixed, check attachment for details

https://github.com/goriyavipul/taskdemo/assets/13375596/11898a10-ad70-4cbd-bcc0-6953c9fbb620

**Comment by henryejemuta** [comment]
So reviewing you code, I figured the Module not found issues is related to your files naming convention, hence it will run on Windows which is case insensitive and encounter errors on Linux (Which I'm currently on) as Linux is case sensitive, when using index like you did for Layout and most of the other component, index has to be in all lowercase not Index.

@goriyavipul  Doing this fix this issue, see video in https://github.com/goriyavipul/taskdemo/issues/3#issue-2180879477 for the solution to this

**Comment by goriyavipul** [comment]
I have changed the file name. Please pull the latest code and try in Linux. I am working in windows so not facing this issue.
