### ISSUE TITLE
Server Error TypeError: getStaticPaths is not a function

### ISSUE THREAD

**Issue by henryejemuta** [goriyavipul/taskdemo#3]
![image](https://github.com/goriyavipul/taskdemo/assets/13375596/1e5f6e02-8b1e-45cb-8b39-5e196f60e115)

It's clear you were trying to debug something here, hence you still had debugger here
![image](https://github.com/goriyavipul/taskdemo/assets/13375596/48d8aff1-bd0c-490f-b39d-d6855b161755)

https://github.com/goriyavipul/taskdemo/assets/13375596/b9f81da6-338a-4c7a-bd87-e9c119b2ef06

**Comment by henryejemuta** [comment]
@goriyavipul FYA, kindly see attached video for your reference

**Comment by goriyavipul** [comment]
It's not a redux issue. I am not facing this issue. It's next js rendering issue from your system. So I request you to do npm i again and hard restart the project and check.

**Comment by goriyavipul** [comment]
All the issue are resolved if you are facing any specif issue in Linux better we can schedule a call and I can show you everything if you are available

**Comment by henryejemuta** [comment]
Fixed
